locals {
  managed_identities = {
    system_assigned_user_assigned = var.managed_identities.system_assigned || length(var.managed_identities.user_assigned_resource_ids) > 0 ? {
      this = {
        type                       = var.managed_identities.system_assigned && length(var.managed_identities.user_assigned_resource_ids) > 0 ? "SystemAssigned, UserAssigned" : length(var.managed_identities.user_assigned_resource_ids) > 0 ? "UserAssigned" : "SystemAssigned"
        user_assigned_resource_ids = var.managed_identities.user_assigned_resource_ids
      }
    } : {}
    system_assigned = var.managed_identities.system_assigned ? {
      this = {
        type = "SystemAssigned"
      }
    } : {}
    user_assigned = length(var.managed_identities.user_assigned_resource_ids) > 0 ? {
      this = {
        type                       = "UserAssigned"
        user_assigned_resource_ids = var.managed_identities.user_assigned_resource_ids
      }
    } : {}
  }
  # Private endpoint application security group associations
  private_endpoint_application_security_group_associations = { for assoc in flatten([
    for pe_k, pe_v in var.private_endpoints : [
      for asg_k, asg_v in pe_v.application_security_group_associations : {
        asg_key         = asg_k
        pe_key          = pe_k
        asg_resource_id = asg_v
      }
    ]
  ]) : "${assoc.pe_key}-${assoc.asg_key}" => assoc }
  resource_body = {
    properties = {
      adminUserEnabled                  = var.admin_user_enabled
      anonymousPullEnabled              = var.anonymous_pull_enabled
      autoGeneratedDomainNameLabelScope = var.auto_generated_domain_name_label_scope
      dataEndpointEnabled               = var.data_endpoint_enabled
      encryption = var.encryption == null ? null : {
        keyVaultProperties = var.encryption.key_vault_properties == null ? null : {
          identity      = var.encryption.key_vault_properties.identity
          keyIdentifier = var.encryption.key_vault_properties.key_identifier
        }
        status = var.encryption.status
      }
      endpointProtocol                 = var.endpoint_protocol
      metadataSearch                   = var.metadata_search
      networkRuleBypassAllowedForTasks = var.network_rule_bypass_allowed_for_tasks
      networkRuleBypassOptions         = var.network_rule_bypass_options
      networkRuleSet = var.network_rule_set == null ? null : {
        defaultAction = var.network_rule_set.default_action
        ipRules = var.network_rule_set.ip_rules == null ? null : [for item in var.network_rule_set.ip_rules : item == null ? null : {
          action = item.action
          value  = item.value
        }]
      }
      policies = var.policies == null ? null : {
        azureADAuthenticationAsArmPolicy = var.policies.azure_ad_authentication_as_arm_policy == null ? null : {
          status = var.policies.azure_ad_authentication_as_arm_policy.status
        }
        exportPolicy = var.policies.export_policy == null ? null : {
          status = var.policies.export_policy.status
        }
        quarantinePolicy = var.policies.quarantine_policy == null ? null : {
          status = var.policies.quarantine_policy.status
        }
        retentionPolicy = var.policies.retention_policy == null ? null : {
          days   = var.policies.retention_policy.days
          status = var.policies.retention_policy.status
        }
        softDeletePolicy = var.policies.soft_delete_policy == null ? null : {
          retentionDays = var.policies.soft_delete_policy.retention_days
          status        = var.policies.soft_delete_policy.status
        }
        trustPolicy = var.policies.trust_policy == null ? null : {
          status = var.policies.trust_policy.status
          type   = var.policies.trust_policy.type
        }
      }
      publicNetworkAccess = var.public_network_access
      regionalEndpoints   = var.regional_endpoints
      roleAssignmentMode  = var.role_assignment_mode
      zoneRedundancy      = var.zone_redundancy
    }
    sku = var.sku == null ? null : {
      name = var.sku.name
    }
  }
  role_definition_resource_substring = "/providers/Microsoft.Authorization/roleDefinitions"
}
